export const GET_COUNTRIES='GET_COUNTRIES'
export const CHANGE_COUNTRY='CHANGE_COUNTRY'
export const GET_COUNTRIES_ERROR='GET_COUNTRIES_ERROR'
export const GET_OVERALL_ERROR='GET_OVERALL_ERROR'
export const GET_OVERALL='GET_OVERALL'
export const SET_COUNTRY='SET_COUNTRY